version: "3"
services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    working_dir: /workspace
    command: sleep infinity
    network_mode: service:db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devcontainer_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
