version: "3"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devcontainer_db
    volumes:
      - db_data:/var/lib/postgresql/data

  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    working_dir: /workspace
    command: sleep infinity
    user: vscode
    depends_on:
      - db

volumes:
  db_data:
